## Churn Prediction: Exploratory Data Analysis

The actual notebooks, contain the EDA for the Ecommerce Customer Behavior Dataset from [kaggle](https://www.kaggle.com/datasets/jenifer201095/ecommerce-customer-behavior-dataset?resource=download "Go to dataset").

### Initial setup

In [27]:
## Load working libraries
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from xgboost import XGBClassifier

In [28]:

## Load dataset
### Set data path
DATA_PATH = "../data/raw/behavior.csv"

### Load the dataset from data path
if os.path.exists(DATA_PATH):
    df = pd.read_csv(DATA_PATH)
    print("✨ Environment and data successfully connected in Positron! ✨")
    print(f"📊 Dataset consists of {df.shape[0]} rows and {df.shape[1]} features.\n")
    display(df.head())
else:
    print(f"❌ Error: Dataset not found at {DATA_PATH}")

✨ Environment and data successfully connected in Positron! ✨
📊 Dataset consists of 25000 rows and 8 features.

,customer_id,avg_session_time,pages_per_session,cart_abandon_rate,return_rate,support_tickets,review_score,behavior_churn_signal
0,CUST000001,8.12,21,0.95,0.37,1,3.39,1
1,CUST000002,3.96,9,0.16,0.03,3,4.46,1
2,CUST000003,12.42,24,0.71,0.01,1,4.88,0
3,CUST000004,16.82,18,0.21,0.09,1,1.73,0
4,CUST000005,6.78,2,0.52,0.22,0,2.16,1

### Basic data integrity check

In [29]:
## Missing values and Target Variable balance check
print("=== 1. Data Types and Missing Values ===")
print(df.info())

print("\n=== 2. Target Variable Balance (Churn Signal) ===")
churn_counts = df['behavior_churn_signal'].value_counts()
churn_percentages = df['behavior_churn_signal'].value_counts(normalize=True) * 100

for val in [0, 1]:
    print(f"Class {val} (Non-Churn/Churn): {churn_counts[val]} rows ({churn_percentages[val]:.2f}%)")

=== 1. Data Types and Missing Values ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            25000 non-null  object
 1   avg_session_time       25000 non-null  float64
 2   pages_per_session      25000 non-null  int64
 3   cart_abandon_rate      25000 non-null  float64
 4   return_rate            25000 non-null  float64
 5   support_tickets        25000 non-null  int64
 6   review_score           25000 non-null  float64
 7   behavior_churn_signal  25000 non-null  int64
dtypes: float64(4), int64(3), object(1)
memory usage: 1.5+ MB
None

=== 2. Target Variable Balance (Churn Signal) ===
Class 0 (Non-Churn/Churn): 16388 rows (65.55%)
Class 1 (Non-Churn/Churn): 8612 rows (34.45%)

In [30]:
## Statistical summary
print("\n=== 3. Statistical Summary ===")
display(df.describe())

=== 3. Statistical Summary ===

,avg_session_time,pages_per_session,cart_abandon_rate,return_rate,support_tickets,review_score,behavior_churn_signal
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,10.468978,13.080840,0.497954,0.250166,5.011960,3.005011,0.344480
std,5.472970,7.225421,0.287699,0.144221,3.171722,1.157417,0.475208
min,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,5.690000,7.000000,0.250000,0.130000,2.000000,2.010000,0.000000
50%,10.490000,13.000000,0.500000,0.250000,5.000000,3.010000,0.000000
75%,15.200000,19.000000,0.750000,0.380000,8.000000,4.010000,1.000000
max,20.000000,25.000000,1.000000,0.500000,10.000000,5.000000,1.000000

### Features Engieneering

In [31]:
## Developing new features
# 1. Frustration Index (High tickets + Low review scores)
df['frustration_index'] = df['support_tickets'] / (df['review_score'] + 0.1)

# 2. Value-to-Bail Ratio (Browsing depth vs. checkout abandonment)
df['value_to_bail'] = df['pages_per_session'] * (1 - df['cart_abandon_rate'])

# 3. Return Defect Risk (Logistical hassle interaction)
df['return_defect_risk'] = df['return_rate'] * df['support_tickets']

print("=== 4. Feature engineering complete! New columns added. ===")
print(df[['frustration_index', 'value_to_bail', 'return_defect_risk']].head())

=== 4. Feature engineering complete! New columns added. ===
   frustration_index  value_to_bail  return_defect_risk
0           0.286533           1.05                0.37
1           0.657895           7.56                0.09
2           0.200803           6.96                0.01
3           0.546448          14.22                0.09
4           0.000000           0.96                0.00

Since the target variable is moderately imbalance, there is not necessary applied sampling methodologies. then, we proceed to train the baseline model.

### Baseline Model training (Logistic Regression)

In [32]:
## Step 1: Split target from features
X = df.drop(columns = ['customer_id', 'behavior_churn_signal']) #dropping customer_id an target
y = df['behavior_churn_signal'] #creating target dataset

print('=== Step 1: Splitting features and target ===')
print(f'X shape: {X.shape} features \ny shape: {y.shape} target')

=== Step 1: Splitting features and target ===
X shape: (25000, 9) features
y shape: (25000,) target

In [33]:
## Step 2: Split train and test using the stratify of y (keep 65/35 ratio)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y)

print('=== Step 2: Splitting train and test with stratifying ===')
print(f'X_train: {X_train.shape} | X_test: {X_test.shape}')
print(f'y_train: {y_train.shape} | y_test: {y_test.shape}')

print(f'\nTrain Churn Ratio: {y_train.value_counts(normalize=True)[1]:.2%}')
print(f'Test Churn Ratio: {y_test.value_counts(normalize=True)[1]:.2%}')

=== Step 2: Splitting train and test with stratifying ===
X_train: (20000, 9) | X_test: (5000, 9)
y_train: (20000,) | y_test: (5000,)

Train Churn Ratio: 34.45%
Test Churn Ratio: 34.44%

In [34]:
## Step 3: Scaling features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

train_means = np.mean(X_train_scaled, axis=0)
train_stds = np.std(X_train_scaled, axis=0)

print("=== Step 3: Scaling and normalization train features ===")
for i in range(6):
    print(f"   Feature {i} -> Mean: {train_means[i]:.4f} (Target: ~0) | Std Dev: {train_stds[i]:.4f} (Target: 1)")

=== Step 3: Scaling and normalization train features ===
   Feature 0 -> Mean: -0.0000 (Target: ~0) | Std Dev: 1.0000 (Target: 1)
   Feature 1 -> Mean: -0.0000 (Target: ~0) | Std Dev: 1.0000 (Target: 1)
   Feature 2 -> Mean: 0.0000 (Target: ~0) | Std Dev: 1.0000 (Target: 1)
   Feature 3 -> Mean: 0.0000 (Target: ~0) | Std Dev: 1.0000 (Target: 1)
   Feature 4 -> Mean: -0.0000 (Target: ~0) | Std Dev: 1.0000 (Target: 1)
   Feature 5 -> Mean: -0.0000 (Target: ~0) | Std Dev: 1.0000 (Target: 1)

In [35]:
## Step 4: Training baseline model (logistic regression)
baseline_model = LogisticRegression(random_state=42)
baseline_model.fit(X_train_scaled, y_train)

LogisticRegression(random_state=42)

In [36]:
## Step 5: Baseline performance report
y_pred = baseline_model.predict(X_test_scaled)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.68      0.92      0.78      3278
           1       0.55      0.18      0.27      1722

    accuracy                           0.67      5000
   macro avg       0.62      0.55      0.53      5000
weighted avg       0.64      0.67      0.61      5000

The model results show that the logistic regression is being effective at predicting customers who are not going to churn (68% precision), while it fails in 82% of the cases that are actually marked for churn. Likewise, the f1-score is well below the expected benchmark (75%). Therefore, the results will not generate added value for the business.

Therefore, we will evaluate a Random Forest model, which is a good option when the target variable is moderatly imbalanced.

### Evaluate contrast model (Random Forest)

In [37]:
## Step 6: Training contrast model (Random Forest)
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, class_weight='balanced')
rf_model.fit(X_train_scaled, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=10, random_state=42)

In [38]:
## Step 7: Contrast performance report
y_pred_rf = rf_model.predict(X_test_scaled)
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.74      0.64      0.69      3278
           1       0.46      0.57      0.51      1722

    accuracy                           0.62      5000
   macro avg       0.60      0.61      0.60      5000
weighted avg       0.64      0.62      0.63      5000

With the application of Random Forest, the performance metrics show effective improvements. The new model is capable of predicting more than half of the actual churn cases; additionally, the F1-score also shows an improvement, indicating that the model is becoming more precise.

To further fine-tune the prediction, we will tune the model's hyperparameters using GridSearchCV.

### Hyperparameter Tuning

In [39]:
## Step 8: Tuning the hyperparameters
### 1. Define the parameter space we want to explore
param_grid = {
    'n_estimators': [100, 200],          # Number of trees in the forest
    'max_depth': [10, 15, None],          # Deepest path allowed in a tree
    'min_samples_split': [2, 5],         # Minimum samples required to split a node
    'min_samples_leaf': [1, 2]           # Minimum samples required at a leaf node
}

### 2. Instantiate the base model with balanced weights
base_rf = RandomForestClassifier(random_state=42, class_weight='balanced')

### 3. Set up the Grid Search using 3-fold Cross-Validation 
# We optimize specifically for 'f1' since that's our business target metric!
grid_search = GridSearchCV(
    estimator=base_rf, 
    param_grid=param_grid, 
    cv=3, 
    scoring='f1', 
    n_jobs=-1, 
    verbose=1
)

### 4. Run the search on our scaled training data
grid_search.fit(X_train_scaled, y_train)

print("\n🏆 OPTIMIZATION COMPLETE 🏆")
print(f"🔥 Best Hyperparameters Found: {grid_search.best_params_}")

### 5. Evaluate the optimized model on our test data
best_rf_model = grid_search.best_estimator_
y_pred_tuned = best_rf_model.predict(X_test_scaled)

print("\n=== 📊 TUNED RANDOM FOREST PERFORMANCE REPORT ===")
print(classification_report(y_test, y_pred_tuned))

Fitting 3 folds for each of 24 candidates, totalling 72 fits

🏆 OPTIMIZATION COMPLETE 🏆
🔥 Best Hyperparameters Found: {'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 200}

=== 📊 TUNED RANDOM FOREST PERFORMANCE REPORT ===
              precision    recall  f1-score   support

           0       0.73      0.64      0.68      3278
           1       0.45      0.56      0.50      1722

    accuracy                           0.61      5000
   macro avg       0.59      0.60      0.59      5000
weighted avg       0.64      0.61      0.62      5000

Since tuning failed to significantly improve the performance metrics of the random forest, we will proceed to test a gradient boosting method, such as xgboost.

### Evaluate second contrast model (xgboost)

In [41]:
## step 9: Training new contrast model
xgb_tuned = XGBClassifier(
    n_estimators=300,          # More trees to let sequential learning complete
    max_depth=8,               # Deeper trees to catch complex interactions
    learning_rate=0.2,         # Faster learning step to adapt to skewed data
    scale_pos_weight=1.9,      # Keeping our balance handle for Class 1
    subsample=0.8,             # Use 80% of rows per tree to reduce overfitting
    colsample_bytree=0.8,      # Use 80% of features per tree to force feature exploration
    random_state=42,
    eval_metric='logloss'
)

xgb_tuned.fit(X_train_scaled, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.2, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=8, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [42]:
## step 10: Contrast performance report
y_pred_xgb = xgb_tuned.predict(X_test_scaled)
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.70      0.73      0.71      3278
           1       0.43      0.40      0.41      1722

    accuracy                           0.61      5000
   macro avg       0.56      0.56      0.56      5000
weighted avg       0.60      0.61      0.61      5000