In [2]:
import os
import pandas as pd

# The relative path from the notebooks/ directory
DATA_PATH = "../data/raw/behavior.csv"

if os.path.exists(DATA_PATH):
    df = pd.read_csv(DATA_PATH)
    print("✨ Environment and data successfully connected in Positron! ✨")
    print(f"📊 Dataset consists of {df.shape[0]} rows and {df.shape[1]} features.\n")
    display(df.head())
else:
    print(f"❌ Error: Dataset not found at {DATA_PATH}")

✨ Environment and data successfully connected in Positron! ✨
📊 Dataset consists of 25000 rows and 8 features.

,customer_id,avg_session_time,pages_per_session,cart_abandon_rate,return_rate,support_tickets,review_score,behavior_churn_signal
0,CUST000001,8.12,21,0.95,0.37,1,3.39,1
1,CUST000002,3.96,9,0.16,0.03,3,4.46,1
2,CUST000003,12.42,24,0.71,0.01,1,4.88,0
3,CUST000004,16.82,18,0.21,0.09,1,1.73,0
4,CUST000005,6.78,2,0.52,0.22,0,2.16,1

In [3]:
# Cell 2: Basic Data Integrity and Class Balance Check

print("=== 1. Data Types and Missing Values ===")
print(df.info())

print("\n=== 2. Statistical Summary ===")
display(df.describe())

print("\n=== 3. Target Variable Balance (Churn Signal) ===")
churn_counts = df['behavior_churn_signal'].value_counts()
churn_percentages = df['behavior_churn_signal'].value_counts(normalize=True) * 100

for val in [0, 1]:
    print(f"Class {val} (Non-Churn/Churn): {churn_counts[val]} rows ({churn_percentages[val]:.2f}%)")

=== 1. Data Types and Missing Values ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            25000 non-null  object
 1   avg_session_time       25000 non-null  float64
 2   pages_per_session      25000 non-null  int64
 3   cart_abandon_rate      25000 non-null  float64
 4   return_rate            25000 non-null  float64
 5   support_tickets        25000 non-null  int64
 6   review_score           25000 non-null  float64
 7   behavior_churn_signal  25000 non-null  int64
dtypes: float64(4), int64(3), object(1)
memory usage: 1.5+ MB
None

=== 2. Statistical Summary ===

,avg_session_time,pages_per_session,cart_abandon_rate,return_rate,support_tickets,review_score,behavior_churn_signal
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,10.468978,13.080840,0.497954,0.250166,5.011960,3.005011,0.344480
std,5.472970,7.225421,0.287699,0.144221,3.171722,1.157417,0.475208
min,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,5.690000,7.000000,0.250000,0.130000,2.000000,2.010000,0.000000
50%,10.490000,13.000000,0.500000,0.250000,5.000000,3.010000,0.000000
75%,15.200000,19.000000,0.750000,0.380000,8.000000,4.010000,1.000000
max,20.000000,25.000000,1.000000,0.500000,10.000000,5.000000,1.000000

=== 3. Target Variable Balance (Churn Signal) ===
Class 0 (Non-Churn/Churn): 16388 rows (65.55%)
Class 1 (Non-Churn/Churn): 8612 rows (34.45%)